<a href="https://colab.research.google.com/github/Srinath77-del/network-intrusion-detection-ml/blob/main/UNSW_NB15_Week3_Model_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving UNSW_NB15_testing-set.csv to UNSW_NB15_testing-set.csv

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("UNSW_NB15_testing-set.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (82332, 45)

In [ ]:
df.head()

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

In [ ]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 82332
Number of columns: 45

In [ ]:
print("Column names:")
for i, column in enumerate(df.columns, start=1):
    print(i, "-", column)

Column names:
1 - id
2 - dur
3 - proto
4 - service
5 - state
6 - spkts
7 - dpkts
8 - sbytes
9 - dbytes
10 - rate
11 - sttl
12 - dttl
13 - sload
14 - dload
15 - sloss
16 - dloss
17 - sinpkt
18 - dinpkt
19 - sjit
20 - djit
21 - swin
22 - stcpb
23 - dtcpb
24 - dwin
25 - tcprtt
26 - synack
27 - ackdat
28 - smean
29 - dmean
30 - trans_depth
31 - response_body_len
32 - ct_srv_src
33 - ct_state_ttl
34 - ct_dst_ltm
35 - ct_src_dport_ltm
36 - ct_dst_sport_ltm
37 - ct_dst_src_ltm
38 - is_ftp_login
39 - ct_ftp_cmd
40 - ct_flw_http_mthd
41 - ct_src_ltm
42 - ct_srv_dst
43 - is_sm_ips_ports
44 - attack_cat
45 - label

In [ ]:
df.dtypes

id                     int64
dur                  float64
proto                 object
service               object
state                 object
spkts                  int64
dpkts                  int64
sbytes                 int64
dbytes                 int64
rate                 float64
sttl                   int64
dttl                   int64
sload                float64
dload                float64
sloss                  int64
dloss                  int64
sinpkt               float64
dinpkt               float64
sjit                 float64
djit                 float64
swin                   int64
stcpb                  int64
dtcpb                  int64
dwin                   int64
tcprtt               float64
synack               float64
ackdat               float64
smean                  int64
dmean                  int64
trans_depth            int64
response_body_len      int64
ct_srv_src             int64
ct_state_ttl           int64
ct_dst_ltm             int64
ct_src_dport_ltm       int64
ct_dst_sport_ltm       int64
ct_dst_src_ltm         int64
is_ftp_login           int64
ct_ftp_cmd             int64
ct_flw_http_mthd       int64
ct_src_ltm             int64
ct_srv_dst             int64
is_sm_ips_ports        int64
attack_cat            object
label                  int64
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82332 entries, 0 to 82331
Data columns (total 45 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 82332 non-null  int64
 1   dur                82332 non-null  float64
 2   proto              82332 non-null  object
 3   service            82332 non-null  object
 4   state              82332 non-null  object
 5   spkts              82332 non-null  int64
 6   dpkts              82332 non-null  int64
 7   sbytes             82332 non-null  int64
 8   dbytes             82332 non-null  int64
 9   rate               82332 non-null  float64
 10  sttl               82332 non-null  int64
 11  dttl               82332 non-null  int64
 12  sload              82332 non-null  float64
 13  dload              82332 non-null  float64
 14  sloss              82332 non-null  int64
 15  dloss              82332 non-null  int64
 16  sinpkt             82332 non-null  float64
 17  dinpkt             82332 non-null  float64
 18  sjit               82332 non-null  float64
 19  djit               82332 non-null  float64
 20  swin               82332 non-null  int64
 21  stcpb              82332 non-null  int64
 22  dtcpb              82332 non-null  int64
 23  dwin               82332 non-null  int64
 24  tcprtt             82332 non-null  float64
 25  synack             82332 non-null  float64
 26  ackdat             82332 non-null  float64
 27  smean              82332 non-null  int64
 28  dmean              82332 non-null  int64
 29  trans_depth        82332 non-null  int64
 30  response_body_len  82332 non-null  int64
 31  ct_srv_src         82332 non-null  int64
 32  ct_state_ttl       82332 non-null  int64
 33  ct_dst_ltm         82332 non-null  int64
 34  ct_src_dport_ltm   82332 non-null  int64
 35  ct_dst_sport_ltm   82332 non-null  int64
 36  ct_dst_src_ltm     82332 non-null  int64
 37  is_ftp_login       82332 non-null  int64
 38  ct_ftp_cmd         82332 non-null  int64
 39  ct_flw_http_mthd   82332 non-null  int64
 40  ct_src_ltm         82332 non-null  int64
 41  ct_srv_dst         82332 non-null  int64
 42  is_sm_ips_ports    82332 non-null  int64
 43  attack_cat         82332 non-null  object
 44  label              82332 non-null  int64
dtypes: float64(11), int64(30), object(4)
memory usage: 28.3+ MB

In [ ]:
print("Label distribution:")
print(df["label"].value_counts())

Label distribution:
label
1    45332
0    37000
Name: count, dtype: int64

In [ ]:
print("Label percentage:")
print(df["label"].value_counts(normalize=True) * 100)

Label percentage:
label
1    55.060001
0    44.939999
Name: proportion, dtype: float64

In [ ]:
print("Attack category distribution:")
print(df["attack_cat"].value_counts())

Attack category distribution:
attack_cat
Normal            37000
Generic           18871
Exploits          11132
Fuzzers            6062
DoS                4089
Reconnaissance     3496
Analysis            677
Backdoor            583
Shellcode           378
Worms                44
Name: count, dtype: int64

In [ ]:
print("Attack category percentage:")
print(df["attack_cat"].value_counts(normalize=True) * 100)

Attack category percentage:
attack_cat
Normal            44.939999
Generic           22.920614
Exploits          13.520867
Fuzzers            7.362872
DoS                4.966477
Reconnaissance     4.246223
Analysis           0.822281
Backdoor           0.708109
Shellcode          0.459117
Worms              0.053442
Name: proportion, dtype: float64

In [ ]:
print("Missing values in each column:")
print(df.isnull().sum())
print("Total missing values:", df.isnull().sum().sum())
print("Number of duplicate rows:", df.duplicated().sum())

Missing values in each column:
id                   0
dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat           0
label                0
dtype: int64
Total missing values: 0
Number of duplicate rows: 0

In [ ]:
categorical_columns = ["proto", "service", "state"]

for column in categorical_columns:
    print("\n", column)
    print("Number of unique values:", df[column].nunique())
    print("Unique values:")
    print(df[column].unique())

 proto
Number of unique values: 131
Unique values:
['udp' 'arp' 'tcp' 'igmp' 'ospf' 'sctp' 'gre' 'ggp' 'ip' 'ipnip' 'st2'
 'argus' 'chaos' 'egp' 'emcon' 'nvp' 'pup' 'xnet' 'mux' 'dcn' 'hmp' 'prm'
 'trunk-1' 'trunk-2' 'xns-idp' 'leaf-1' 'leaf-2' 'irtp' 'rdp' 'netblt'
 'mfe-nsp' 'merit-inp' '3pc' 'idpr' 'ddp' 'idpr-cmtp' 'tp++' 'ipv6' 'sdrp'
 'ipv6-frag' 'ipv6-route' 'idrp' 'mhrp' 'i-nlsp' 'rvd' 'mobile' 'narp'
 'skip' 'tlsp' 'ipv6-no' 'any' 'ipv6-opts' 'cftp' 'sat-expak' 'ippc'
 'kryptolan' 'sat-mon' 'cpnx' 'wsn' 'pvp' 'br-sat-mon' 'sun-nd' 'wb-mon'
 'vmtp' 'ttp' 'vines' 'nsfnet-igp' 'dgp' 'eigrp' 'tcf' 'sprite-rpc' 'larp'
 'mtp' 'ax.25' 'ipip' 'aes-sp3-d' 'micp' 'encap' 'pri-enc' 'gmtp' 'ifmp'
 'pnni' 'qnx' 'scps' 'cbt' 'bbn-rcc' 'igp' 'bna' 'swipe' 'visa' 'ipcv'
 'cphb' 'iso-tp4' 'wb-expak' 'sep' 'secure-vmtp' 'xtp' 'il' 'rsvp' 'unas'
 'fc' 'iso-ip' 'etherip' 'pim' 'aris' 'a/n' 'ipcomp' 'snp' 'compaq-peer'
 'ipx-n-ip' 'pgm' 'vrrp' 'l2tp' 'zero' 'ddx' 'iatp' 'stp' 'srp' 'uti' 'sm'
 'smp' 'isis' 'ptp' 'fire' 'crtp' 'crudp' 'sccopmce' 'iplt' 'pipe' 'sps'
 'ib']

 service
Number of unique values: 13
Unique values:
['-' 'http' 'ftp' 'ftp-data' 'smtp' 'pop3' 'dns' 'snmp' 'ssl' 'dhcp' 'irc'
 'radius' 'ssh']

 state
Number of unique values: 7
Unique values:
['INT' 'FIN' 'REQ' 'ACC' 'CON' 'RST' 'CLO']

In [ ]:
numeric_columns = df.select_dtypes(include=["int64", "float64"]).columns

print("Number of numerical columns:", len(numeric_columns))

df[numeric_columns].describe().T

Number of numerical columns: 41

,count,mean,std,min,25%,50%,75%,max
id,82332.0,4.116650e+04,2.376735e+04,1.0,20583.750000,4.116650e+04,6.174925e+04,8.233200e+04
dur,82332.0,1.006756e+00,4.710444e+00,0.0,0.000008,1.413800e-02,7.193603e-01,5.999999e+01
spkts,82332.0,1.866647e+01,1.339164e+02,1.0,2.000000,6.000000e+00,1.200000e+01,1.064600e+04
dpkts,82332.0,1.754594e+01,1.155741e+02,0.0,0.000000,2.000000e+00,1.000000e+01,1.101800e+04
sbytes,82332.0,7.993908e+03,1.716423e+05,24.0,114.000000,5.340000e+02,1.280000e+03,1.435577e+07
dbytes,82332.0,1.323379e+04,1.514715e+05,0.0,0.000000,1.780000e+02,9.560000e+02,1.465753e+07
rate,82332.0,8.241089e+04,1.486204e+05,0.0,28.606114,2.650177e+03,1.111111e+05,1.000000e+06
sttl,82332.0,1.809677e+02,1.015134e+02,0.0,62.000000,2.540000e+02,2.540000e+02,2.550000e+02
dttl,82332.0,9.571300e+01,1.166677e+02,0.0,0.000000,2.900000e+01,2.520000e+02,2.530000e+02
sload,82332.0,6.454902e+07,1.798618e+08,0.0,11202.466797,5.770032e+05,6.514286e+07,5.268000e+09
dload,82332.0,6.305470e+05,2.393001e+06,0.0,0.000000,2.112951e+03,1.585808e+04,2.082111e+07
sloss,82332.0,4.753692e+00,6.464962e+01,0.0,0.000000,1.000000e+00,3.000000e+00,5.319000e+03
dloss,82332.0,6.308556e+00,5.570802e+01,0.0,0.000000,0.000000e+00,2.000000e+00,5.507000e+03
sinpkt,82332.0,7.553943e+02,6.182616e+03,0.0,0.008000,5.579285e-01,6.340944e+01,6.000999e+04
dinpkt,82332.0,1.217013e+02,1.292378e+03,0.0,0.000000,1.000000e-02,6.313637e+01,5.773924e+04
sjit,82332.0,6.363075e+03,5.672402e+04,0.0,0.000000,1.762392e+01,3.219332e+03,1.483831e+06
djit,82332.0,5.351804e+02,3.635305e+03,0.0,0.000000,0.000000e+00,1.284599e+02,4.631992e+05
swin,82332.0,1.334591e+02,1.273570e+02,0.0,0.000000,2.550000e+02,2.550000e+02,2.550000e+02
stcpb,82332.0,1.084642e+09,1.390860e+09,0.0,0.000000,2.788886e+07,2.171310e+09,4.294950e+09
dtcpb,82332.0,1.073465e+09,1.381996e+09,0.0,0.000000,2.856975e+07,2.144205e+09,4.294881e+09
dwin,82332.0,1.282866e+02,1.274914e+02,0.0,0.000000,2.550000e+02,2.550000e+02,2.550000e+02
tcprtt,82332.0,5.592504e-02,1.160218e-01,0.0,0.000000,5.510000e-04,1.055407e-01,3.821465e+00
synack,82332.0,2.925593e-02,7.085352e-02,0.0,0.000000,4.410000e-04,5.259550e-02,3.226788e+00
ackdat,82332.0,2.666912e-02,5.509354e-02,0.0,0.000000,8.000000e-05,4.881625e-02,2.928778e+00
smean,82332.0,1.395286e+02,2.084721e+02,24.0,57.000000,6.500000e+01,1.000000e+02,1.504000e+03
dmean,82332.0,1.162751e+02,2.446003e+02,0.0,0.000000,4.400000e+01,8.700000e+01,1.500000e+03
trans_depth,82332.0,9.427683e-02,5.429218e-01,0.0,0.000000,0.000000e+00,0.000000e+00,1.310000e+02
response_body_len,82332.0,1.595372e+03,3.806697e+04,0.0,0.000000,0.000000e+00,0.000000e+00,5.242880e+06
ct_srv_src,82332.0,9.546604e+00,1.109029e+01,1.0,2.000000,5.000000e+00,1.100000e+01,6.300000e+01
ct_state_ttl,82332.0,1.369273e+00,1.067188e+00,0.0,1.000000,1.000000e+00,2.000000e+00,6.000000e+00
ct_dst_ltm,82332.0,5.744923e+00,8.418112e+00,1.0,1.000000,2.000000e+00,6.000000e+00,5.900000e+01
ct_src_dport_ltm,82332.0,4.928898e+00,8.389545e+00,1.0,1.000000,1.000000e+00,4.000000e+00,5.900000e+01
ct_dst_sport_ltm,82332.0,3.663011e+00,5.915386e+00,1.0,1.000000,1.000000e+00,3.000000e+00,3.800000e+01
ct_dst_src_ltm,82332.0,7.456360e+00,1.141519e+01,1.0,1.000000,3.000000e+00,6.000000e+00,6.300000e+01
is_ftp_login,82332.0,8.283535e-03,9.117119e-02,0.0,0.000000,0.000000e+00,0.000000e+00,2.000000e+00
ct_ftp_cmd,82332.0,8.380703e-03,9.248508e-02,0.0,0.000000,0.000000e+00,0.000000e+00,2.000000e+00
ct_flw_http_mthd,82332.0,1.297430e-01,6.386826e-01,0.0,0.000000,0.000000e+00,0.000000e+00,1.600000e+01
ct_src_ltm,82332.0,6.468360e+00,8.543927e+00,1.0,1.000000,3.000000e+00,7.000000e+00,6.000000e+01
ct_srv_dst,82332.0,9.164262e+00,1.112141e+01,1.0,2.000000,5.000000e+00,1.100000e+01,6.200000e+01
is_sm_ips_ports,82332.0,1.112569e-02,1.048906e-01,0.0,0.000000,0.000000e+00,0.000000e+00,1.000000e+00
label,82332.0,5.506000e-01,4.974361e-01,0.0,0.000000,1.000000e+00,1.000000e+00,1.000000e+00

In [ ]:
numeric_features = df.select_dtypes(include=["int64", "float64"]).columns

# Exclude ID and target from outlier analysis
numeric_features = numeric_features.drop(["id", "label"])

outlier_summary = []

for column in numeric_features:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = ((df[column] < lower_bound) | (df[column] > upper_bound)).sum()

    outlier_summary.append({
        "Feature": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Bound": lower_bound,
        "Upper Bound": upper_bound,
        "Outlier Count": outliers,
        "Outlier %": (outliers / len(df)) * 100
    })

outlier_df = pd.DataFrame(outlier_summary)

outlier_df = outlier_df.sort_values(
    by="Outlier Count",
    ascending=False
)

outlier_df

,Feature,Q1,Q3,IQR,Lower Bound,Upper Bound,Outlier Count,Outlier %
9,dload,0.000000,1.585808e+04,1.585808e+04,-2.378712e+04,3.964521e+04,18112,21.998737
32,ct_dst_src_ltm,1.000000,6.000000e+00,5.000000e+00,-6.500000e+00,1.350000e+01,12789,15.533450
4,dbytes,0.000000,9.560000e+02,9.560000e+02,-1.434000e+03,2.390000e+03,12308,14.949230
23,smean,57.000000,1.000000e+02,4.300000e+01,-7.500000e+00,1.645000e+02,11928,14.487684
30,ct_src_dport_ltm,1.000000,4.000000e+00,3.000000e+00,-3.500000e+00,8.500000e+00,11476,13.938687
11,dloss,0.000000,2.000000e+00,2.000000e+00,-3.000000e+00,5.000000e+00,11272,13.690910
31,ct_dst_sport_ltm,1.000000,3.000000e+00,2.000000e+00,-2.000000e+00,6.000000e+00,10907,13.247583
29,ct_dst_ltm,1.000000,6.000000e+00,5.000000e+00,-6.500000e+00,1.350000e+01,10479,12.727736
1,spkts,2.000000,1.200000e+01,1.000000e+01,-1.300000e+01,2.700000e+01,10196,12.384006
27,ct_srv_src,2.000000,1.100000e+01,9.000000e+00,-1.150000e+01,2.450000e+01,10093,12.258903
37,ct_srv_dst,2.000000,1.100000e+01,9.000000e+00,-1.150000e+01,2.450000e+01,10040,12.194529
24,dmean,0.000000,8.700000e+01,8.700000e+01,-1.305000e+02,2.175000e+02,9902,12.026915
36,ct_src_ltm,1.000000,7.000000e+00,6.000000e+00,-8.000000e+00,1.600000e+01,9579,11.634601
3,sbytes,114.000000,1.280000e+03,1.166000e+03,-1.635000e+03,3.029000e+03,9270,11.259292
2,dpkts,0.000000,1.000000e+01,1.000000e+01,-1.500000e+01,2.500000e+01,8907,10.818394
15,djit,0.000000,1.284599e+02,1.284599e+02,-1.926899e+02,3.211498e+02,8573,10.412719
25,trans_depth,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7582,9.209056
35,ct_flw_http_mthd,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7580,9.206627
8,sload,11202.466797,6.514286e+07,6.513165e+07,-9.768628e+07,1.628403e+08,6715,8.156003
14,sjit,0.000000,3.219332e+03,3.219332e+03,-4.828999e+03,8.048331e+03,6321,7.677452
5,rate,28.606114,1.111111e+05,1.110825e+05,-1.665951e+05,2.777349e+05,6201,7.531701
0,dur,0.000008,7.193603e-01,7.193523e-01,-1.079020e+00,1.798389e+00,5868,7.127241
12,sinpkt,0.008000,6.340944e+01,6.340144e+01,-9.509417e+01,1.585116e+02,5668,6.884322
26,response_body_len,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5657,6.870961
10,sloss,0.000000,3.000000e+00,3.000000e+00,-4.500000e+00,7.500000e+00,5499,6.679056
13,dinpkt,0.000000,6.313637e+01,6.313637e+01,-9.470455e+01,1.578409e+02,4717,5.729243
21,synack,0.000000,5.259550e-02,5.259550e-02,-7.889325e-02,1.314887e-01,2954,3.587912
22,ackdat,0.000000,4.881625e-02,4.881625e-02,-7.322437e-02,1.220406e-01,2480,3.012195
20,tcprtt,0.000000,1.055407e-01,1.055407e-01,-1.583111e-01,2.638519e-01,2020,2.453481
28,ct_state_ttl,1.000000,2.000000e+00,1.000000e+00,-5.000000e-01,3.500000e+00,1833,2.226352
38,is_sm_ips_ports,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,916,1.112569
34,ct_ftp_cmd,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,680,0.825924
33,is_ftp_login,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,678,0.823495
6,sttl,62.000000,2.540000e+02,1.920000e+02,-2.260000e+02,5.420000e+02,0,0.000000
19,dwin,0.000000,2.550000e+02,2.550000e+02,-3.825000e+02,6.375000e+02,0,0.000000
7,dttl,0.000000,2.520000e+02,2.520000e+02,-3.780000e+02,6.300000e+02,0,0.000000
16,swin,0.000000,2.550000e+02,2.550000e+02,-3.825000e+02,6.375000e+02,0,0.000000
17,stcpb,0.000000,2.171310e+09,2.171310e+09,-3.256964e+09,5.428274e+09,0,0.000000
18,dtcpb,0.000000,2.144205e+09,2.144205e+09,-3.216308e+09,5.360513e+09,0,0.000000

In [ ]:
numeric_features = df.select_dtypes(include=["int64", "float64"]).columns

# Exclude ID because it is an identifier, not a predictive feature
numeric_features = numeric_features.drop("id")

correlation_with_label = (
    df[numeric_features]
    .corr()["label"]
    .drop("label")
    .sort_values(key=abs, ascending=False)
)

print("Correlation of numerical features with label:")
print(correlation_with_label)

Correlation of numerical features with label:
sttl                 0.504159
swin                -0.414504
ct_dst_sport_ltm     0.393668
dwin                -0.369257
ct_src_dport_ltm     0.341513
rate                 0.328629
ct_state_ttl         0.318517
ct_srv_dst           0.292931
ct_srv_src           0.290195
dtcpb               -0.282860
stcpb               -0.281428
dload               -0.280534
ct_dst_src_ltm       0.279989
ct_src_ltm           0.276494
ct_dst_ltm           0.257995
dmean               -0.211544
synack              -0.149944
tcprtt              -0.148800
sload                0.124548
sinpkt              -0.120768
ackdat              -0.120522
is_sm_ips_ports     -0.117407
dttl                -0.098591
ct_flw_http_mthd    -0.075028
dpkts               -0.061515
smean               -0.061146
dloss               -0.044399
dinpkt              -0.037585
dbytes              -0.032632
spkts               -0.027731
sjit                -0.027397
djit                -0.027131
trans_depth         -0.025804
sbytes               0.020641
ct_ftp_cmd          -0.017138
response_body_len   -0.016414
is_ftp_login        -0.016206
sloss                0.006360
dur                 -0.001145
Name: label, dtype: float64

In [ ]:
numeric_features = df.select_dtypes(include=["int64", "float64"]).columns
numeric_features = numeric_features.drop(["id", "label"])

corr_matrix = df[numeric_features].corr().abs()

# Keep only the upper triangle
upper_triangle = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

# Find highly correlated feature pairs
high_corr_pairs = (
    upper_triangle
    .stack()
    .reset_index()
)

high_corr_pairs.columns = ["Feature 1", "Feature 2", "Correlation"]

high_corr_pairs = high_corr_pairs[
    high_corr_pairs["Correlation"] >= 0.80
].sort_values(
    by="Correlation",
    ascending=False
)

print("Highly correlated feature pairs (|correlation| >= 0.80):")
print(high_corr_pairs)

Highly correlated feature pairs (|correlation| >= 0.80):
            Feature 1         Feature 2  Correlation
152            dbytes             dloss     0.997109
117            sbytes             sloss     0.995027
726      is_ftp_login        ct_ftp_cmd     0.994341
83              dpkts             dloss     0.981506
684        ct_srv_src        ct_srv_dst     0.977849
76              dpkts            dbytes     0.976419
46              spkts             sloss     0.973644
39              spkts            sbytes     0.965750
696        ct_dst_ltm  ct_src_dport_ltm     0.960401
490              swin              dwin     0.960125
415            sinpkt   is_sm_ips_ports     0.944506
724    ct_dst_src_ltm        ct_srv_dst     0.941047
570            tcprtt            synack     0.939473
679        ct_srv_src    ct_dst_src_ltm     0.933795
710  ct_src_dport_ltm        ct_src_ltm     0.933172
702        ct_dst_ltm        ct_src_ltm     0.932252
705  ct_src_dport_ltm  ct_dst_sport_ltm     0.911637
571            tcprtt            ackdat     0.897688
706  ct_src_dport_ltm    ct_dst_src_ltm     0.876030
697        ct_dst_ltm  ct_dst_sport_ltm     0.872185
698        ct_dst_ltm    ct_dst_src_ltm     0.868150
711  ct_src_dport_ltm        ct_srv_dst     0.863614
677        ct_srv_src  ct_src_dport_ltm     0.855472
703        ct_dst_ltm        ct_srv_dst     0.855158
717  ct_dst_sport_ltm        ct_src_ltm     0.847314
676        ct_srv_src        ct_dst_ltm     0.842195
723    ct_dst_src_ltm        ct_src_ltm     0.840012
713  ct_dst_sport_ltm    ct_dst_src_ltm     0.830993
683        ct_srv_src        ct_src_ltm     0.822486
738        ct_src_ltm        ct_srv_dst     0.822407
718  ct_dst_sport_ltm        ct_srv_dst     0.810954
678        ct_srv_src  ct_dst_sport_ltm     0.801164

In [ ]:
print("Number of rows:", len(df))
print("Number of unique IDs:", df["id"].nunique())
print("Duplicate IDs:", df["id"].duplicated().sum())
print("Minimum ID:", df["id"].min())
print("Maximum ID:", df["id"].max())

Number of rows: 82332
Number of unique IDs: 82332
Duplicate IDs: 0
Minimum ID: 1
Maximum ID: 82332

In [ ]:
print(pd.crosstab(df["attack_cat"], df["label"]))

label               0      1
attack_cat
Analysis            0    677
Backdoor            0    583
DoS                 0   4089
Exploits            0  11132
Fuzzers             0   6062
Generic             0  18871
Normal          37000      0
Reconnaissance      0   3496
Shellcode           0    378
Worms               0     44

In [ ]:
input_df = df.drop(columns=["id", "attack_cat", "label"])

numerical_features = input_df.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = input_df.select_dtypes(include=["object"]).columns.tolist()

print("Total input features:", len(input_df.columns))
print("\nNumerical features:", len(numerical_features))
print(numerical_features)

print("\nCategorical features:", len(categorical_features))
print(categorical_features)

Total input features: 42

Numerical features: 39
['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports']

Categorical features: 3
['proto', 'service', 'state']

In [ ]:
for col in ["proto", "service", "state"]:
    print(f"\n===== {col.upper()} =====")
    print(df[col].value_counts().head(20))

===== PROTO =====
proto
tcp        43095
udp        29418
unas        3515
arp          987
ospf         676
sctp         324
any           96
gre           88
rsvp          64
ipv6          61
sep           58
sun-nd        54
swipe         52
mobile        52
pim           52
xns-idp       34
leaf-1        34
bbn-rcc       34
prm           34
irtp          33
Name: count, dtype: int64

===== SERVICE =====
service
-           47153
dns         21367
http         8287
smtp         1851
ftp          1552
ftp-data     1396
pop3          423
ssh           204
ssl            30
snmp           29
dhcp           26
radius          9
irc             5
Name: count, dtype: int64

===== STATE =====
state
FIN    39339
INT    34163
CON     6982
REQ     1842
ACC        4
RST        1
CLO        1
Name: count, dtype: int64

In [ ]:
for col in ["proto", "service", "state"]:
    print(f"\n===== {col.upper()} =====")
    counts = df[col].value_counts()
    percentages = df[col].value_counts(normalize=True) * 100

    result = pd.DataFrame({
        "Count": counts,
        "Percentage": percentages.round(4)
    })

    print(result)
numerical_features = df.select_dtypes(
    include=["int64", "float64"]
).columns.drop(["id", "label"])

skewness = df[numerical_features].skew().sort_values(
    ascending=False
)

print("Most positively skewed features:")
print(skewness.head(15))

print("\nMost negatively skewed features:")
print(skewness.tail(15))
range_analysis = pd.DataFrame({
    "Minimum": df[numerical_features].min(),
    "Maximum": df[numerical_features].max(),
    "Mean": df[numerical_features].mean(),
    "Std": df[numerical_features].std()
})

range_analysis["Range"] = (
    range_analysis["Maximum"] - range_analysis["Minimum"]
)

print(range_analysis.sort_values(
    by="Range",
    ascending=False
).head(20))
target_correlation = (
    df[numerical_features]
    .corrwith(df["label"])
    .sort_values(key=abs, ascending=False)
)

feature_ranking = pd.DataFrame({
    "Correlation_with_Label": target_correlation,
    "Absolute_Correlation": target_correlation.abs()
})

print("Top 20 numerical features related to label:")
print(feature_ranking.head(20))
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

X = df.drop(columns=["id", "attack_cat", "label"])
y = df["label"]

numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numerical_features),
        ("cat", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ), categorical_features)
    ]
)

X_transformed = preprocessor.fit_transform(X)

print("Original feature count:", X.shape[1])
print("Transformed feature count:", X_transformed.shape[1])
print("Transformed data shape:", X_transformed.shape)
print("========== WEEK 2 DATA ANALYSIS SUMMARY ==========")

print("Rows:", df.shape[0])
print("Original columns:", df.shape[1])

print("\nMissing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())

print("\nTarget distribution:")
print(df["label"].value_counts())

print("\nExcluded columns:")
print(["id", "attack_cat"])

print("\nNumerical input features:", len(numerical_features))
print("Categorical input features:", len(categorical_features))

print("\nCategorical features:")
print(categorical_features)

print("\nTransformed feature count:", X_transformed.shape[1])

print("\n========== END SUMMARY ==========")

===== PROTO =====
          Count  Percentage
proto
tcp       43095     52.3430
udp       29418     35.7309
unas       3515      4.2693
arp         987      1.1988
ospf        676      0.8211
...         ...         ...
sccopmce     32      0.0389
sps          32      0.0389
pipe         32      0.0389
ib           31      0.0377
igmp         30      0.0364

[131 rows x 2 columns]

===== SERVICE =====
          Count  Percentage
service
-         47153     57.2718
dns       21367     25.9522
http       8287     10.0653
smtp       1851      2.2482
ftp        1552      1.8851
ftp-data   1396      1.6956
pop3        423      0.5138
ssh         204      0.2478
ssl          30      0.0364
snmp         29      0.0352
dhcp         26      0.0316
radius        9      0.0109
irc           5      0.0061

===== STATE =====
       Count  Percentage
state
FIN    39339     47.7809
INT    34163     41.4942
CON     6982      8.4803
REQ     1842      2.2373
ACC        4      0.0049
RST        1      0.0012
CLO        1      0.0012
Most positively skewed features:
trans_depth          170.794394
response_body_len     74.635200
djit                  60.562275
dloss                 54.465649
sbytes                53.778546
dbytes                52.550387
sloss                 52.465277
dpkts                 49.304127
spkts                 47.747777
dinpkt                23.013046
sjit                  15.349380
synack                13.809682
ct_flw_http_mthd      12.557680
ct_ftp_cmd            11.243182
is_ftp_login          11.042308
dtype: float64

Most negatively skewed features:
dmean               3.106839
ct_src_dport_ltm    2.856818
ct_dst_ltm          2.667001
ct_dst_sport_ltm    2.506801
ct_src_ltm          2.437292
ct_dst_src_ltm      2.189041
ct_srv_dst          1.898853
ct_srv_src          1.856368
ct_state_ttl        1.522167
dtcpb               0.930137
stcpb               0.916447
dttl                0.575208
dwin               -0.012329
swin               -0.093574
sttl               -0.690381
dtype: float64
                   Minimum       Maximum          Mean           Std  \
sload                  0.0  5.268000e+09  6.454902e+07  1.798618e+08
stcpb                  0.0  4.294950e+09  1.084642e+09  1.390860e+09
dtcpb                  0.0  4.294881e+09  1.073465e+09  1.381996e+09
dload                  0.0  2.082111e+07  6.305470e+05  2.393001e+06
dbytes                 0.0  1.465753e+07  1.323379e+04  1.514715e+05
sbytes                24.0  1.435577e+07  7.993908e+03  1.716423e+05
response_body_len      0.0  5.242880e+06  1.595372e+03  3.806697e+04
sjit                   0.0  1.483831e+06  6.363075e+03  5.672402e+04
rate                   0.0  1.000000e+06  8.241089e+04  1.486204e+05
djit                   0.0  4.631992e+05  5.351804e+02  3.635305e+03
sinpkt                 0.0  6.000999e+04  7.553943e+02  6.182616e+03
dinpkt                 0.0  5.773924e+04  1.217013e+02  1.292378e+03
dpkts                  0.0  1.101800e+04  1.754594e+01  1.155741e+02
spkts                  1.0  1.064600e+04  1.866647e+01  1.339164e+02
dloss                  0.0  5.507000e+03  6.308556e+00  5.570802e+01
sloss                  0.0  5.319000e+03  4.753692e+00  6.464962e+01
dmean                  0.0  1.500000e+03  1.162751e+02  2.446003e+02
smean                 24.0  1.504000e+03  1.395286e+02  2.084721e+02
sttl                   0.0  2.550000e+02  1.809677e+02  1.015134e+02
swin                   0.0  2.550000e+02  1.334591e+02  1.273570e+02

                          Range
sload              5.268000e+09
stcpb              4.294950e+09
dtcpb              4.294881e+09
dload              2.082111e+07
dbytes             1.465753e+07
sbytes             1.435575e+07
response_body_len  5.242880e+06
sjit               1.483831e+06
rate               1.000000e+06
djit               4.631992e+05
sinpkt             6.000999e+04
dinpkt             5.773924e+04
dpkts              1.101800e+04
spkts              1.064500e+04
dloss              5.507000e+03
sloss              5.319000e+03
dmean              1.500000e+03
smean              1.480000e+03
sttl               2.550000e+02
swin               2.550000e+02
Top 20 numerical features related to label:
                  Correlation_with_Label  Absolute_Correlation
sttl                            0.504159              0.504159
swin                           -0.414504              0.414504
ct_dst_sport_ltm                0.393668              0.393668
dwin                           -0.369257              0.369257
ct_src_dport_ltm                0.341513              0.341513
rate                            0.328629              0.328629
ct_state_ttl                    0.318517              0.318517
ct_srv_dst                      0.292931              0.292931
ct_srv_src                      0.290195              0.290195
dtcpb                          -0.282860              0.282860
stcpb                          -0.281428              0.281428
dload                          -0.280534              0.280534
ct_dst_src_ltm                  0.279989              0.279989
ct_src_ltm                      0.276494              0.276494
ct_dst_ltm                      0.257995              0.257995
dmean                          -0.211544              0.211544
synack                         -0.149944              0.149944
tcprtt                         -0.148800              0.148800
sload                           0.124548              0.124548
sinpkt                         -0.120768              0.120768
Original feature count: 42
Transformed feature count: 190
Transformed data shape: (82332, 190)
========== WEEK 2 DATA ANALYSIS SUMMARY ==========
Rows: 82332
Original columns: 45

Missing values: 0
Duplicate rows: 0

Target distribution:
label
1    45332
0    37000
Name: count, dtype: int64

Excluded columns:
['id', 'attack_cat']

Numerical input features: 39
Categorical input features: 3

Categorical features:
['proto', 'service', 'state']

Transformed feature count: 190

========== END SUMMARY ==========

In [3]:
from google.colab import files

uploaded = files.upload()

Saving UNSW_NB15_testing-set.csv to UNSW_NB15_testing-set.csv

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("UNSW_NB15_testing-set.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (82332, 45)

In [5]:
print("Target distribution:")
print(df["label"].value_counts())

Target distribution:
label
1    45332
0    37000
Name: count, dtype: int64

In [6]:
y = df["label"]

X = df.drop(columns=["id", "attack_cat", "label"])

print("Input feature shape:", X.shape)
print("Target shape:", y.shape)

print("\nInput features:")
print(X.columns.tolist())

print("\nTarget distribution:")
print(y.value_counts())

Input feature shape: (82332, 42)
Target shape: (82332,)

Input features:
['dur', 'proto', 'service', 'state', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports']

Target distribution:
label
1    45332
0    37000
Name: count, dtype: int64

In [7]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set:")
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)

print("\nTesting set:")
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

print("\nTraining target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training set:
X_train shape: (65865, 42)
y_train shape: (65865,)

Testing set:
X_test shape: (16467, 42)
y_test shape: (16467,)

Training target distribution:
label
1    36265
0    29600
Name: count, dtype: int64

Testing target distribution:
label
1    9067
0    7400
Name: count, dtype: int64

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features = ["proto", "service", "state"]

numerical_features = [
    col for col in X.columns
    if col not in categorical_features
]

print("Number of numerical features:", len(numerical_features))
print("Number of categorical features:", len(categorical_features))

print("\nCategorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numerical_features)

# Create preprocessing transformer
preprocessor = ColumnTransformer(
    transformers=[
        (
            "categorical",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        ),
        (
            "numerical",
            "passthrough",
            numerical_features
        )
    ]
)

print("\nPreprocessing pipeline created successfully!")

Number of numerical features: 39
Number of categorical features: 3

Categorical features:
['proto', 'service', 'state']

Numerical features:
['dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports']

Preprocessing pipeline created successfully!

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

decision_tree_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", DecisionTreeClassifier(
            random_state=42,
            max_depth=10
        ))
    ]
)

print("Decision Tree pipeline created successfully!")

# Train the model
decision_tree_model.fit(X_train, y_train)

print("Decision Tree model trained successfully!")

Decision Tree pipeline created successfully!
Decision Tree model trained successfully!

In [10]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

y_pred_dt = decision_tree_model.predict(X_test)

accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)

print("===== DECISION TREE RESULTS =====")
print(f"Accuracy : {accuracy_dt:.4f}")
print(f"Precision: {precision_dt:.4f}")
print(f"Recall   : {recall_dt:.4f}")
print(f"F1-Score : {f1_dt:.4f}")

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(y_test, y_pred_dt))

print("===== CONFUSION MATRIX =====")
cm_dt = confusion_matrix(y_test, y_pred_dt)
print(cm_dt)

===== DECISION TREE RESULTS =====
Accuracy : 0.9597
Precision: 0.9752
Recall   : 0.9510
F1-Score : 0.9630

===== CLASSIFICATION REPORT =====
              precision    recall  f1-score   support

           0       0.94      0.97      0.96      7400
           1       0.98      0.95      0.96      9067

    accuracy                           0.96     16467
   macro avg       0.96      0.96      0.96     16467
weighted avg       0.96      0.96      0.96     16467

===== CONFUSION MATRIX =====
[[7181  219]
 [ 444 8623]]

In [11]:

y_train_pred_dt = decision_tree_model.predict(X_train)

train_accuracy_dt = accuracy_score(y_train, y_train_pred_dt)
test_accuracy_dt = accuracy_score(y_test, y_pred_dt)

print("===== OVERFITTING CHECK =====")
print(f"Training Accuracy: {train_accuracy_dt:.4f}")
print(f"Testing Accuracy : {test_accuracy_dt:.4f}")
print(f"Accuracy Difference: {train_accuracy_dt - test_accuracy_dt:.4f}")

===== OVERFITTING CHECK =====
Training Accuracy: 0.9681
Testing Accuracy : 0.9597
Accuracy Difference: 0.0084

In [12]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("classifier", RandomForestClassifier(
            n_estimators=100,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

print("Random Forest pipeline created successfully!")

random_forest_model.fit(X_train, y_train)

print("Random Forest model trained successfully!")

Random Forest pipeline created successfully!
Random Forest model trained successfully!

In [13]:
y_pred_rf = random_forest_model.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)

print("===== RANDOM FOREST RESULTS =====")
print(f"Accuracy : {accuracy_rf:.4f}")
print(f"Precision: {precision_rf:.4f}")
print(f"Recall   : {recall_rf:.4f}")
print(f"F1-Score : {f1_rf:.4f}")

print("\n===== CLASSIFICATION REPORT =====")
print(classification_report(y_test, y_pred_rf))

print("===== CONFUSION MATRIX =====")
cm_rf = confusion_matrix(y_test, y_pred_rf)
print(cm_rf)

===== RANDOM FOREST RESULTS =====
Accuracy : 0.9769
Precision: 0.9840
Recall   : 0.9739
F1-Score : 0.9789

===== CLASSIFICATION REPORT =====
              precision    recall  f1-score   support

           0       0.97      0.98      0.97      7400
           1       0.98      0.97      0.98      9067

    accuracy                           0.98     16467
   macro avg       0.98      0.98      0.98     16467
weighted avg       0.98      0.98      0.98     16467

===== CONFUSION MATRIX =====
[[7256  144]
 [ 237 8830]]

In [14]:
y_train_pred_rf = random_forest_model.predict(X_train)

train_accuracy_rf = accuracy_score(y_train, y_train_pred_rf)
test_accuracy_rf = accuracy_score(y_test, y_pred_rf)

print("Training Accuracy:", round(train_accuracy_rf, 4))
print("Testing Accuracy :", round(test_accuracy_rf, 4))
print("Accuracy Difference:", round(train_accuracy_rf - test_accuracy_rf, 4))

Training Accuracy: 1.0
Testing Accuracy : 0.9769
Accuracy Difference: 0.0231

In [15]:
comparison = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest"],
    "Accuracy": [accuracy_dt, accuracy_rf],
    "Precision": [precision_dt, precision_rf],
    "Recall": [recall_dt, recall_rf],
    "F1-Score": [f1_dt, f1_rf]
})

print(comparison.round(4).to_string(index=False))

        Model  Accuracy  Precision  Recall  F1-Score
Decision Tree    0.9597     0.9752  0.9510    0.9630
Random Forest    0.9769     0.9840  0.9739    0.9789

In [16]:
feature_names = random_forest_model.named_steps["preprocessor"].get_feature_names_out()
importances = random_forest_model.named_steps["classifier"].feature_importances_

feature_importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values("Importance", ascending=False)

print("Top 20 features:")
print(feature_importance.head(20).to_string(index=False))

Top 20 features:
                    Feature  Importance
  numerical__ct_dst_src_ltm    0.081020
          numerical__sbytes    0.061136
            numerical__sttl    0.052854
           numerical__smean    0.045411
      numerical__ct_srv_dst    0.045249
           numerical__sload    0.042702
    numerical__ct_state_ttl    0.037961
           numerical__dmean    0.035079
numerical__ct_dst_sport_ltm    0.034092
             numerical__dur    0.032941
          numerical__dbytes    0.032155
          numerical__dinpkt    0.031946
          numerical__tcprtt    0.030517
          numerical__synack    0.030480
            numerical__dttl    0.029960
           numerical__dload    0.029765
      numerical__ct_srv_src    0.029002
          numerical__sinpkt    0.026808
            numerical__rate    0.026350
           numerical__dpkts    0.024000

In [17]:
sample_data = X_test.iloc[:10]

sample_predictions = random_forest_model.predict(sample_data)

prediction_results = pd.DataFrame({
    "Actual": y_test.iloc[:10].values,
    "Predicted": sample_predictions
})

print(prediction_results.to_string(index=False))

 Actual  Predicted
      1          1
      1          1
      0          0
      0          0
      1          1
      0          0
      1          1
      0          0
      1          1
      0          0

In [18]:
try:
    invalid_data = X_test.iloc[:5, :10]
    random_forest_model.predict(invalid_data)
except Exception as e:
    print("Prediction failed.")
    print("Error type:", type(e).__name__)
    print("Error message:", str(e))

Prediction failed.
Error type: ValueError
Error message: columns are missing: {'ct_state_ttl', 'response_body_len', 'djit', 'ct_src_ltm', 'ct_ftp_cmd', 'smean', 'ct_srv_src', 'dmean', 'swin', 'dinpkt', 'stcpb', 'sinpkt', 'sloss', 'synack', 'ct_dst_sport_ltm', 'is_ftp_login', 'sload', 'dwin', 'ct_srv_dst', 'is_sm_ips_ports', 'sjit', 'dtcpb', 'ct_dst_src_ltm', 'dttl', 'ct_dst_ltm', 'ackdat', 'dloss', 'ct_flw_http_mthd', 'dload', 'ct_src_dport_ltm', 'trans_depth', 'tcprtt'}

In [20]:
required_features = X.columns.tolist()

def validate_input(data):
    missing_features = set(required_features) - set(data.columns)

    if missing_features:
        print("Invalid input.")
        print("Missing features:", sorted(missing_features))
        return False

    print("Input validation successful.")
    return True

validate_input(X_test.iloc[:5])

Input validation successful.

True

In [21]:
invalid_data = X_test.iloc[:5, :10]

validate_input(invalid_data)

Invalid input.
Missing features: ['ackdat', 'ct_dst_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'ct_flw_http_mthd', 'ct_ftp_cmd', 'ct_src_dport_ltm', 'ct_src_ltm', 'ct_srv_dst', 'ct_srv_src', 'ct_state_ttl', 'dinpkt', 'djit', 'dload', 'dloss', 'dmean', 'dtcpb', 'dttl', 'dwin', 'is_ftp_login', 'is_sm_ips_ports', 'response_body_len', 'sinpkt', 'sjit', 'sload', 'sloss', 'smean', 'stcpb', 'swin', 'synack', 'tcprtt', 'trans_depth']

False

In [22]:
valid_data = X_test.iloc[:5]

if validate_input(valid_data):
    predictions = random_forest_model.predict(valid_data)
    print("Predictions:", predictions)

Input validation successful.
Predictions: [1 1 0 0 1]

In [23]:
import joblib

joblib.dump(random_forest_model, "random_forest_nids_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [24]:
loaded_model = joblib.load("random_forest_nids_model.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [25]:
loaded_predictions = loaded_model.predict(X_test)

loaded_accuracy = accuracy_score(y_test, loaded_predictions)

print("Loaded model accuracy:", round(loaded_accuracy, 4))

Loaded model accuracy: 0.9769

In [26]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_rf).ravel()

print("True Negatives :", tn)
print("False Positives:", fp)
print("False Negatives:", fn)
print("True Positives :", tp)

True Negatives : 7256
False Positives: 144
False Negatives: 237
True Positives : 8830

In [27]:
attack_detection_rate = tp / (tp + fn)

print("Attack Detection Rate:", round(attack_detection_rate, 4))
print("Attack Detection Rate (%):", round(attack_detection_rate * 100, 2))

Attack Detection Rate: 0.9739
Attack Detection Rate (%): 97.39

In [28]:
final_results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1-Score"],
    "Decision Tree": [
        accuracy_dt,
        precision_dt,
        recall_dt,
        f1_dt
    ],
    "Random Forest": [
        accuracy_rf,
        precision_rf,
        recall_rf,
        f1_rf
    ]
})

final_results["Decision Tree"] = (final_results["Decision Tree"] * 100).round(2)
final_results["Random Forest"] = (final_results["Random Forest"] * 100).round(2)

print(final_results.to_string(index=False))

   Metric  Decision Tree  Random Forest
 Accuracy          95.97          97.69
Precision          97.52          98.40
   Recall          95.10          97.39
 F1-Score          96.30          97.89

In [29]:
final_results.to_csv("week3_model_results.csv", index=False)

print("Model results saved successfully!")

Model results saved successfully!

In [30]:
print("========== WEEK 3 FINAL SUMMARY ==========")

print("Dataset records:", len(X))
print("Training records:", len(X_train))
print("Testing records:", len(X_test))

print("\nDecision Tree Accuracy:", f"{accuracy_dt * 100:.2f}%")
print("Random Forest Accuracy:", f"{accuracy_rf * 100:.2f}%")

print("\nRandom Forest Precision:", f"{precision_rf * 100:.2f}%")
print("Random Forest Recall:", f"{recall_rf * 100:.2f}%")
print("Random Forest F1-Score:", f"{f1_rf * 100:.2f}%")

print("\nFalse Positives:", fp)
print("False Negatives:", fn)

print("\nTop Feature:", feature_importance.iloc[0]["Feature"])
print("Top Feature Importance:", round(feature_importance.iloc[0]["Importance"], 6))

print("\nSaved Model: random_forest_nids_model.pkl")
print("Saved Results: week3_model_results.csv")

print("\n========== END OF WEEK 3 ==========")

========== WEEK 3 FINAL SUMMARY ==========
Dataset records: 82332
Training records: 65865
Testing records: 16467

Decision Tree Accuracy: 95.97%
Random Forest Accuracy: 97.69%

Random Forest Precision: 98.40%
Random Forest Recall: 97.39%
Random Forest F1-Score: 97.89%

False Positives: 144
False Negatives: 237

Top Feature: numerical__ct_dst_src_ltm
Top Feature Importance: 0.08102

Saved Model: random_forest_nids_model.pkl
Saved Results: week3_model_results.csv

========== END OF WEEK 3 ==========